# Generated by Django 4.2.4 on 2023-09-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task_detail', models.TextField(max_length=50)),
                ('is_complete', models.BooleanField(default=False)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
